[package]
name = "compiler"
version = "0.1.0"
authors = ["MartinBrathen <marbrt-6@ltu.student.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.0.1"
nom_locate = "1.0.0"
regex = "1.3.1"
